
services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    networks:
      private-testnet_custom_net:
      
  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    networks:
      private-testnet_custom_net:
      
  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    networks:
      private-testnet_custom_net:
      
  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
    networks:
      private-testnet_custom_net:
      
  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    networks:
      private-testnet_custom_net:
      
  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    networks:
      private-testnet_custom_net:
      
  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    networks:
      private-testnet_custom_net:
      
  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init
    networks:
      private-testnet_custom_net:
      
  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    networks:
      private-testnet_custom_net:
      
  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    networks:
      private-testnet_custom_net:
      
  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    networks:
      private-testnet_custom_net:
      
  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    networks:
      private-testnet_custom_net:
      
networks:
  private-testnet_custom_net:
    external: true        
      
